language: python
python:
  # "2.6" -- no "unittest discover"
  - "2.7"
  # "3.2" --  u'unicode' was illegal here
  # "3.3..3.4" -- skipped
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  #- "3.10" -- not yet..
  - "nightly"

# Optional command to install dependencies:
#install: "pip install -r requirements.txt"
install: pip install coverage flake8

# Command to run tests:
script:
  - NO_EXTERNAL_REQUESTS=1 python -m coverage run
      --include='exactonline/*' --omit='*_test.py' runtests.py
  - flake8 --max-complexity=9 .
  - python -m coverage report --show-missing --fail-under 50
